import type { NextPage } from "next";
import Head from "next/head";
import { Box } from "../components/Box";
import { Flex } from "../components/Flex";
import { Header } from "../components/Header";
import NextImage from "next/image";
import { css } from "../../stitches.config";
import { Section } from "../components/Section";
import { Button } from "../components/Button";
import { Grid } from "../components/Grid";

const Home: NextPage = () => {
  const title = css({
    variants: {
      variant: {
        main: {
          fontSize: "$9",
          color: "White",
          fontWeight: "bolder",
          fontFamily: "Inter",
        },
        secondary: {
          fontSize: "$7",
          color: "White",
          fontWeight: "bolder",
          fontFamily: "Inter",
        },
      },
    },
  });

  const paragraph = css({
    variants: {
      variant: {
        main: {
          fontSize: "$1",
          color: "#898CA9",
          fontFamily: "Inter",
          marginTop: "$3",
          marginBottom: "$4",
          textAlign: "center",
          lineHeight: 1.5,
        },
      },
    },
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>
        <Header />
        <Box
          css={{
            position: "absolute",
            top: 0,
            right: 0,
            bottom: 0,
            left: 0,
            zIndex: -1,
          }}
        >
          <NextImage
            objectFit="cover"
            src="/bg-img.svg"
            layout="fill"
            quality={100}
            alt="background"
          />
        </Box>
        <Section
          css={{
            maxWidth: "1145px",
            margin: "0 auto",
          }}
        >
          <Flex
            direction="column"
            justify="between"
            align="center"
            css={{ marginBottom: "$9" }}
          >
            <h1 className={title({ variant: "main" })}>
              We make crypto <br /> clear and simple
            </h1>
            <p className={paragraph({ variant: "main" })}>
              Buy, sell, and grow your crypto with CoinFlip,
              the platform dedicated <br /> to every trader at every level.
            </p>
            <Button
              css={{ width: "120px", padding: "$2" }}
              variant="gradientBluePurple"
            >
              Get Started
            </Button>
          </Flex>

          <Grid columns={3} gap={3} justify="between">
            <Box
              css={{
                background: "#1A1B23",
                borderRadius: "20px",
                textAlign: "center",
                marginTop: "$7",
                paddingTop: "$4",
                paddingBottom: "$7",
                paddingLeft: "$8",
                paddingRight: "$8",
                zIndex: -5,
              }}
            >
              <NextImage
                src="/arrow-left-right.svg"
                width={70}
                height={70}
                objectFit="contain"
              />
              <h2 className={title({ variant: "secondary" })}>Trade Desk</h2>
              <p className={paragraph({ variant: "main" })}>
                Invest in crypto anytime, anywhere with our safe, secure, and
                easy to use online platform
              </p>
              <Button variant="purple">Get Started &#8594;</Button>
            </Box>

            <Box
              css={{
                background: "#1A1B23",
                borderRadius: "20px",
                textAlign: "center",
                marginTop: "$7",
                paddingTop: "$4",
                paddingBottom: "$7",
                paddingLeft: "$8",
                paddingRight: "$8",
                zIndex: -5,
              }}
            >
              <NextImage
                src="/coin-flip-atm.svg"
                width={70}
                height={70}
                objectFit="contain"
              />
              <h2 className={title({ variant: "secondary" })}>CoinFlip ATMs</h2>
              <p className={paragraph({ variant: "main" })}>
                We have thousands of ATMs located across the U.S. where you can
                easily convert cash to crypto
              </p>
              <Button variant="purple">Find an ATM &#8594;</Button>
            </Box>

            <Box
              css={{
                background: "#1A1B23",
                borderRadius: "20px",
                textAlign: "center",
                marginTop: "$7",
                paddingTop: "$4",
                paddingBottom: "$7",
                paddingLeft: "$3",
                paddingRight: "$3",
                zIndex: -5,
              }}
            >
              <NextImage
                src="/coin-flip-wallet.svg"
                width={70}
                height={70}
                objectFit="contain"
              />
              <h2 className={title({ variant: "secondary" })}>
                CoinFlip Wallet
              </h2>
              <p className={paragraph({ variant: "main" })}>
                Store your growing investments in our non-custodial wallet that
                gives you access to a full suite of DeFi services in one place
              </p>

              <Button variant="purple">Download the App &#8594;</Button>
            </Box>
          </Grid>
        </Section>

        <Section css={{ position: "relative" }}>
          <Box
            css={{
              position: "absolute",
              top: 0,
              right: 0,
              bottom: 0,
              zIndex: -1,
            }}
          >
            <NextImage
              objectFit="cover"
              width={670}
              height={500}
              src="/swirl.svg"
              quality={100}
              alt="background"
            />
          </Box>
          <Box
            css={{
              position: "absolute",
              top: 150,
              right: 180,
              bottom: 0,
              zIndex: -1,
            }}
          >
            <NextImage
              objectFit="cover"
              width={50}
              height={50}
              src="/star.svg"
              quality={100}
              alt="background"
            />
          </Box>

          <Box css={{ textAlign: "center" }}>
            <h2 className={title({ variant: "secondary" })}>
              A crypto investment platform <br /> that invests in you
            </h2>
            <p className={paragraph({ variant: "main" })}>
              We invest more resources than any other platrom in making sure
              great <br /> support from real people is a click away, whenever
              you need it.
            </p>
            <Button
              css={{ width: "120px", padding: "$2" }}
              variant="gradientBluePurple"
            >
              Get Started
            </Button>
          </Box>
        </Section>

        <Section></Section>
      </Box>
    </>
  );
};

export default Home;
